/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 chatIcon.gltf --transform 
Files: chatIcon.gltf [106.63KB] > C:\Users\mohan\Downloads\chat_icon\chatIcon-transformed.glb [61.66KB] (42%)
Author: palymotion (https://sketchfab.com/palymotion)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chat-icon-76c43f69ee41483a953c5070d86ad0a9
Title: Chat Icon
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/chatIcon-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_5.geometry}
        material={materials.Plastic_2}
        position={[0, 0.137, -0.01]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1, 1, 0.7]}
      />
      <mesh
        geometry={nodes.Object_10.geometry}
        material={materials.Matte}
        position={[0.05, 0.136, 0.011]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.11, 0.022, 0.11]}
      />
      <mesh
        geometry={nodes.Object_12.geometry}
        material={materials.Matte_0}
        position={[0, 0.136, 0.011]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.11, 0.022, 0.11]}
      />
      <mesh
        geometry={nodes.Object_14.geometry}
        material={materials.Matte_1}
        position={[-0.05, 0.136, 0.011]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.11, 0.022, 0.11]}
      />
    </group>
  );
}

useGLTF.preload("/chatIcon-transformed.glb");
